import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * Abstract base entity providing common fields for all database entities.
 *
 * Every entity in the DRMS system should extend this class to inherit
 * standardized `id`, `createdAt`, and `updatedAt` columns.
 */
export abstract class BaseEntity {
  /** Unique identifier (UUID v4), auto-generated by the database. */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** Timestamp indicating when the record was created. */
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  /** Timestamp indicating when the record was last updated. */
  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
